apps:
  usps-track:
    command: 'bin/usps-track'
    plugs:
      - 'home'
      - 'network'
      - 'network-bind'
base: 'core24'
confinement: 'strict'
contact: 'https://github.com/Tatsh/usps-track/issues'
description: 'Quickly track via SMS several USPS (and some international) tracking numbers via the command line.'
donation: 'https://buymeacoffee.com/Tatsh'
grade: 'stable'
issues: 'https://github.com/Tatsh/usps-track/issues'
license: 'MIT'
name: 'usps-track'
parts:
  usps-track:
    build-packages: []
    plugin: 'python'
    python-packages:
      - '.'
    source: '.'
    stage-packages: []
platforms:
  amd64:
    build-on: 'amd64'
  arm64:
    build-on: 'arm64'
source-code: 'https://github.com/Tatsh/usps-track'
summary: 'Quickly track USPS and international packages via the command line.'
title: 'usps-track'
version: '0.0.5'
website: 'https://tatsh.github.io/usps-track/'
